
WORLD world;
AREA area00,area01,area10,area11,area02,area12,area20,area21,area22;
CONDITION condDummy,condMisson,condKillNPC,condDestroyComp,condWin;
RESULT resMission,resKeyAppear,resKeyAppearMsg,resWinMsg,resEndGame,resExpl1,resExpl2,resExpl3;
GOAL goal;
PLAYER pc;

int CreateWorld(LPWORLD world)
{
	LPNPC npc;
	LPOBJECT itemKey2,itemComputer;

	world->attr=0;
	world->id=0;
	world->name="LEVEL 1";
	world->sizeX=3;
	world->sizeY=3;
	world->sizeZ=1;
	if (!(world->worldMap=(AREA**)malloc(sizeof(AREA*)*(world->sizeX)*(world->sizeY)*(world->sizeZ))))
		return FAILURE;

	// hardcode some areas
	CreateArea( &area00, &area00L0[0][0], &area00L1[0][0], &area00E[0][0], area00EG ); world->worldMap[0]=&area00;
	CreateArea( &area01, &area01L0[0][0], &area01L1[0][0], &area01E[0][0], area01EG ); world->worldMap[1]=&area01;
	CreateArea( &area02, &area02L0[0][0], &area02L1[0][0], &area02E[0][0], area02EG ); world->worldMap[2]=&area02;
	CreateArea( &area10, &area10L0[0][0], &area10L1[0][0], &area10E[0][0], area10EG ); world->worldMap[3]=&area10;
	CreateArea( &area11, &area11L0[0][0], &area11L1[0][0], &area11E[0][0], area11EG ); world->worldMap[4]=&area11;
	CreateArea( &area12, &area12L0[0][0], &area12L1[0][0], &area12E[0][0], area12EG ); world->worldMap[5]=&area12;
	CreateArea( &area20, &area20L0[0][0], &area20L1[0][0], &area20E[0][0], area20EG ); world->worldMap[6]=&area20;
	CreateArea( &area21, &area21L0[0][0], &area21L1[0][0], &area21E[0][0], area21EG ); world->worldMap[7]=&area21;
	CreateArea( &area22, &area22L0[0][0], &area22L1[0][0], &area22E[0][0], area22EG ); world->worldMap[8]=&area22;

	// add some items
	AddItem(&area00,ID_WEP_GUN,0,500,500,NULL,0);
	//AddItem(&area01,ID_ITEM_AID,0,128,300,NULL,1);
	//...doors
	int door1data0[6]={1,0,0,84,175,1};
	AddItem(&area00,ID_TRANS_DOORW,0,736,175,door1data0,0);
	int door1data1[6]={0,0,0,684,175,1};
	AddItem(&area01,ID_TRANS_DOORE,0,32,175,door1data1,0);
	int door2data0[6]={2,2,0,84,400,2};
	AddItem(&area21,ID_TRANS_DOORW,0,736,400,door2data0,0);
	int door2data1[6]={1,2,0,684,400,2};
	AddItem(&area22,ID_TRANS_DOORE,0,32,400,door2data1,0);
	//...keys
	int key1data=2;
	itemKey2=AddItem(&area00,ID_ITEM_KEYCARD,0,625,300,&key1data,0);
	itemKey2->visible=itemKey2->enabled=0;
	key1data=1;
	AddItem(&area11,ID_ITEM_KEYCARD,0,625,400,&key1data,0);
	//
	AddItem(&area00,ID_AMMO_BULLETS,0,350,300,NULL,AMMO_DEFAULTAMNT);
	AddItem(&area21,ID_AMMO_BULLETS,0,350,300,NULL,AMMO_DEFAULTAMNT);
	AddItem(&area22,ID_AMMO_BULLETS,0,350,350,NULL,2*AMMO_DEFAULTAMNT);
	AddItem(&area00,ID_AMMO_BULLETS,0,350,300,NULL,AMMO_DEFAULTAMNT);
	AddItem(&area20,ID_WEP_EXPLOSIVES,0,400,350,NULL,1);
	AddItem(&area00,ID_AMMO_GRENADES,0,350,350,NULL,AMMO_DEFAULTAMNT);
	AddItem(&area00,ID_AMMO_GRENADES,0,350,350,NULL,AMMO_DEFAULTAMNT);
	AddItem(&area01,ID_WEP_GRENADELAUNCH,0,100,100,NULL,0);
	AddItem(&area11,ID_WEP_SHOTGUN,0,625,400,NULL,0);
	AddItem(&area22,ID_WEP_MACHINEGUN,0,600,500,NULL,0);
	AddItem(&area00,ID_ITEM_SILENCER,0,680,550,NULL,0);
	int targ_data[4]={ID_TARGET_TAKE_SHOCK_DAMAGE|ID_TARGET_TAKE_FIRE_DAMAGE,50,100,100};
	itemComputer=AddItem(&area02,ID_ITEM_TARGETAREA,0,400,0,targ_data,0);

	//add enemy soldiera with scripts
	// AREA 00
	npc=CreateNPC(0,500,550,world,0,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	LPNPC npcToKill=CreateNPC(0,600,100,world,0,0,0,1,((rand()%3)+1)*5);
	AddNPC(npcToKill);
	AddScriptInstruct(npcToKill,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npcToKill,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npcToKill,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npcToKill,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npcToKill,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npcToKill,AI_SCRIPT_MOVERIGHT64);
	// AREA 01
	npc=CreateNPC(0,100,100,world,1,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,600,300,world,1,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	// AREA 02
	npc=CreateNPC(0,200,100,world,2,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	npc=CreateNPC(0,650,100,world,2,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	npc=CreateNPC(0,600,400,world,2,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	npc=CreateNPC(0,400,350,world,2,0,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	// AREA 10
	npc=CreateNPC(0,100,100,world,0,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,500,100,world,0,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	npc=CreateNPC(0,275,450,world,0,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	// AREA 11
	npc=CreateNPC(0,300,100,world,1,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	npc=CreateNPC(0,300,350,world,1,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	npc=CreateNPC(0,275,450,world,1,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	// AREA 12
	npc=CreateNPC(0,300,100,world,2,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,400,100,world,2,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,600,100,world,2,1,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	// AREA 20
	npc=CreateNPC(0,475,350,world,0,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,275,350,world,0,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,525,270,world,0,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	npc=CreateNPC(0,100,100,world,0,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	// AREA 21
	npc=CreateNPC(0,200,100,world,1,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	npc=CreateNPC(0,500,300,world,1,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	npc=CreateNPC(0,275,400,world,1,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEUP64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVEDOWN64);
	// AREA 22
	npc=CreateNPC(0,100,100,world,2,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	npc=CreateNPC(0,700,500,world,2,2,0,1,((rand()%3)+1)*5);
	AddNPC(npc);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVELEFT64);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKLEFT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKRIGHT);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKUP);
	AddScriptInstruct(npc,AI_SCRIPT_WAIT30);
	AddScriptInstruct(npc,AI_SCRIPT_LOOKDOWN);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	AddScriptInstruct(npc,AI_SCRIPT_MOVERIGHT64);
	//

	// setup a goal //
	// RESULTS ///////////////////////////////////
	resMission.type=RESTYPE_SHOW_MESSAGE;
	resMission.data=(int*)malloc(sizeof(int)*5);
	int msgdata3[5]={7,250,200,300,100};
	memcpy(resMission.data,msgdata3,sizeof(int)*5);
	resMission.messages=(char**)malloc(sizeof(char*)*msgdata3[0]);
	resMission.messages[0]="\\ART/A001.BMP\0\\0296\0\\0154\0\\0400\0\\0025\0  Stepping out of the jungle you come upon a large clearing. To the east is what seems to be a lightly fortified depot or supply warehouse that would be otherwise inconspicuous if you ignore that it is in the middle of the Luzon.\n...";
	resMission.messages[1]="\\ART/A001.BMP\0\\0296\0\\0154\0\\0400\0\\0025\0  Several guards patrol this area of the clearing but you are, for the moment, out of sight; hidden behind a large amount of foliage.\n...";
	resMission.messages[2]="  You are recieving a message on your tranciever...it is your commanding officer, only known to you as \"The General\".\n...";
	resMission.messages[3]="\\ART/A000.BMP\0\\0040\0\\0155\0\\0390\0\\0205\0  A voice begins to crackle over the speaker...\n  Commander, we have your position from your beacon and will rendezvous with you after your job is finished.\n...";
	resMission.messages[4]="\\ART/A000.BMP\0\\0040\0\\0155\0\\0390\0\\0205\0  Your mission, should you choose to accept it, is to infiltrate the enemy base and disable their supercomputer code-named \"Xerces\".  It has come to our attention that sensitive intelligence information containing US launch codes and several covert bunker locations are in the process of being decrypted on that machine.\n...";
	resMission.messages[5]="\\ART/A000.BMP\0\\0040\0\\0155\0\\0390\0\\0205\0  We know, at least, that the information has not been duplicated but I do not need to tell you that this information being made public would be unfortunate.\n  Should you be captured, you are to disavow any knowledge of this mission.\n...";
	resMission.messages[6]="\\ART/A000.BMP\0\\0040\0\\0155\0\\0390\0\\0205\0  We've assertained from satellite imagery, that said target is located in the eastern portion of the compound.\n  You must first aquire a plastic explsove charge to destroy it, which we have inexplicably not provided to you.\n  Also, you are to maintain radio silence for the duration of this mission.\n  Good luck commander.\n  Over.";
	resMission.next=NULL;
	//
	resKeyAppear.type=RESTYPE_MAKE_ENABLED_VISIBLE;
	resKeyAppear.item=itemKey2;
	resKeyAppear.data=NULL;
	resKeyAppear.messages=NULL;
	resKeyAppear.next=&resKeyAppearMsg;
	//
	resKeyAppearMsg.type=RESTYPE_SHOW_MESSAGE;
	resKeyAppearMsg.data=(int*)malloc(sizeof(int)*5);
	int msgdata[5]={1,150,150,150,50};
	memcpy(resKeyAppearMsg.data,msgdata,sizeof(int)*5);
	resKeyAppearMsg.messages=(char**)malloc(sizeof(char*)*1);
	resKeyAppearMsg.messages[0]="The guard has dropped a key card.";
	resKeyAppearMsg.next=NULL;
	//
	resWinMsg.type=RESTYPE_SHOW_MESSAGE;
	resWinMsg.data=(int*)malloc(sizeof(int)*5);
	int msgdata2[5]={1,150,150,150,50};
	memcpy(resWinMsg.data,msgdata2,sizeof(int)*5);
	resWinMsg.messages=(char**)malloc(sizeof(char*)*1);
	resWinMsg.messages[0]="Congratulations, you have completed your mission!!";
	resWinMsg.next=&resExpl1;
	//
	resEndGame.type=RESTYPE_ENDGAME;
	resEndGame.data=NULL;
	resEndGame.messages=NULL;
	resEndGame.next=NULL;
	//
	int expldata1[2]={350,0};
	int expldata2[2]={450,0};
	int expldata3[2]={400,40};
	resExpl1.type=RESTYPE_EXPLOSION;
	resExpl1.messages=NULL;
	resExpl1.area=&area02;
	resExpl1.data=(int*)malloc(sizeof(int)*2);
	memcpy(resExpl1.data,expldata1,sizeof(int)*2);
	resExpl1.next=&resExpl2;
	resExpl2.type=RESTYPE_EXPLOSION;
	resExpl2.messages=NULL;
	resExpl2.area=&area02;
	resExpl2.data=(int*)malloc(sizeof(int)*2);
	memcpy(resExpl2.data,expldata2,sizeof(int)*2);
	resExpl2.next=&resExpl3;
	resExpl3.type=RESTYPE_EXPLOSION;
	resExpl3.messages=NULL;
	resExpl3.area=&area02;
	resExpl3.data=(int*)malloc(sizeof(int)*2);
	memcpy(resExpl3.data,expldata3,sizeof(int)*2);
	resExpl3.next=NULL;
	// CONDITIONS /////////////////////////////////
	condKillNPC.type=CONTYPE_NPC_KILLED;
	condKillNPC.satisfied=0;
	condKillNPC.npc=npcToKill;
	condKillNPC.data=NULL;
	condKillNPC.result=&resKeyAppear;
	condKillNPC.numNextConditions=1;
	condKillNPC.nextConditions[0]=&condDestroyComp;
	//
	condDestroyComp.type=CONTYPE_TARGET_DESTROYED;
	condDestroyComp.satisfied=0;
	condDestroyComp.item=itemComputer;
	condDestroyComp.data=NULL;
	condDestroyComp.numNextConditions=1;
	condDestroyComp.nextConditions[0]=&condWin;
	condDestroyComp.conditionList=NULL;
	condDestroyComp.result=&resWinMsg;
	//
	condWin.type=CONTYPE_TIMER;
	condWin.satisfied=0;
	condWin.conditionList=NULL;
	condWin.numNextConditions=0;
	condWin.data=(int*)malloc(sizeof(int)*1);
	condWin.data[0]=60;
	condWin.result=&resEndGame;
	//
	condMisson.type=CONTYPE_TIMER;
	condMisson.satisfied=0;
	condMisson.conditionList=NULL;
	condMisson.numNextConditions=0;
	condMisson.data=(int*)malloc(sizeof(int)*1);
	condMisson.data[0]=1;
	condMisson.result=&resMission;
	//
	condDummy.type=0;
	condDummy.satisfied=1;
	condDummy.data=NULL;
	condDummy.conditionList=NULL;
	condDummy.numNextConditions=2;
	condDummy.nextConditions[0]=&condKillNPC;
	condDummy.nextConditions[1]=&condMisson;
	//
	goal.internConditions=NULL;
	goal.conditionTree=&condDummy;
	goal.uid=1;
	//
	// end goal //

	return SUCCESS;
}

int FreeWorld(LPWORLD world)
{
	int i,j;
	//destroy areas/world map
	LPAREA pArea;
	int worldSize=world->sizeX*world->sizeY*world->sizeZ;
	for(i=0; i<worldSize; i++) {
		pArea=world->worldMap[i];
		for (j=0; j<pArea->invent->size; j++) {
			FREE(pArea->invent->list[j]->attr);
			free(pArea->invent->list[j]);
		}
		free(pArea->invent);
	}
	free(world->worldMap);	//free the world!!
	//
	FREE(condKillNPC.data);
	DEL(condKillNPC.conditionList);
	//
	FREE(resKeyAppear.messages);
	FREE(resKeyAppear.data);
	//
	if (goal.internConditions==NULL)
		delete goal.internConditions;
	//
	return SUCCESS;
}


