
DWORD area00EG = AE_OUTSIDE_DEF;
DWORD area10EG = AE_OUTSIDE_DEF;
DWORD area20EG = AE_OUTSIDE_DEF;
DWORD area01EG = AE_INSIDE_DEF;
DWORD area11EG = AE_INSIDE_DEF;
DWORD area21EG = AE_INSIDE_DEF;
DWORD area02EG = AE_INSIDE_DEF;
DWORD area12EG = AE_INSIDE_DEF;
DWORD area22EG = AE_INSIDE_DEF;

