#ifndef __DEFINES_H__
#define __DEFINES_H__


#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define COLORS 256
#define COLOR_DEPTH 8
#define TRANSPARENT_COLOR 253
#define PRIMARY_SURFACE_WIDTH 640
#define PRIMARY_SURFACE_HEIGHT 480
#define STAR_COUNT 1000

#endif