#ifndef __DEFINES_H__
#define __DEFINES_H__


#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define COLORS 256
#define COLOR_DEPTH 8
#define TRANSPARENT_COLOR 253
#define WORLD_WIDTH 1280
#define WORLD_HEIGHT 480
#define SCREEN_OFFSET 220
#define CONTAINED_SCREEN_LEFT 220
#define CONTAINED_SCREEN_RIGHT 859
#define CONTAINED_SCREEN_TOP 0
#define CONTAINED_SCREEN_BOTTOM 479
#define STAR_COUNT 999
#define MAX_OBJECT_EVENTS 99
#define MAX_OBJECT_INSTANCES 99
#define MAX_FIRE_INSTANCES 99

enum ObjectType{BLIP_OBJECT=0, GROUND_CANNON_OBJECT, OBJECT_COUNT};
enum SpriteType{SHIP_SPRITE=0, SHIP_UP_SPRITE, SHIP_DOWN_SPRITE,
		SHIP_DYING_SPRITE, BLIP_SPRITE, BLIP_DYING_SPRITE, 
		GROUND_CANNON_SPRITE, GROUND_CANNON_DYING_SPRITE, 
		SPRITE_COUNT};
enum ObjEventId{BLIP_DEFAULT_ACTION=0, OBJ_EVENT_ID_COUNT};
enum ShipState{SHIP_NORMAL=0, SHIP_UP, SHIP_DOWN, SHIP_DYING};
enum FireType{SHIP_LASER_1=0, FIRE_COUNT};

#define    KeyDown(data, n)    ((data[n] & 0x80) ? true : false)
#define    KeyUp(data, n)    ((data[n] & 0x80) ? false : true)

#endif